import { pagesEn } from "./pages/en";
import { pagesHe } from "./pages/he";

export type Language = "en" | "he";

export type SiteContent = (typeof siteContent)[Language];

export const siteContent = {
  en: {
    nav: {
      logo: "Pura Shalom",
      home: "Home",
      rooms: "Rooms & Cabins",
      holidays: "Holidays & Stays",
      pesach: "Pesach Retreat",
      sukkot: "Sukkot Retreat",
      yearRound: "Year-Round Stays",
      kosherJewishLife: "Dining",
      costaRicaGuide: "Costa Rica Guide",
      faq: "FAQ",
      contact: "Contact",
      planYourStay: "Plan Your Stay",
      diningKashrut: "Dining & Kashrut",
      jewishLife: "Jewish Life",
      experiences: "Experiences",
      searchPlaceholder: "Search",
      phone: "",
      phoneAria: "Call Pura Shalom",
      contactLinkAria: "Contact us",
      menuOpenAria: "Open menu",
      menuCloseAria: "Close menu",
      /** @deprecated legacy tab navigation — preserved for LegacyTabApp */
      discover: "Discover",
      planner: "Plan Your Retreat",
      inquiries: "My Inquiries",
      chat: "Concierge AI",
      cta: "Request Availability",
    },
    pages: pagesEn,
    hero: {
      eyebrow: "Cartago, Costa Rica",
      titleBefore: "A Luxury Kosher Retreat in the ",
      titleEmphasis: "Mountains",
      titleAfter: " of Costa Rica",
      ctaPrimary: "Plan Your Stay",
      ctaSecondary: "View Rooms",
      scroll: "Scroll",
    },
    promise: {
      eyebrow: "Thoughtful Hospitality",
      title: "You arrive. We've already taken care of the rest.",
      body: "From kosher planning to a calm mountain setting, we handle every detail so you can arrive with confidence and ease.",
      cards: [
        {
          title: "Kosher Dining",
          body: "We'll go over kosher standards when you reach out. Our chefs build every menu around your family's needs and the season of your stay.",
        },
        {
          title: "Jewish Life",
          body: "Jewish life support is available on request, with Shabbat-friendly hospitality woven into every stay.",
        },
        {
          title: "Family Retreat",
          body: "A family-friendly retreat with spacious lodging, quiet corners, and programming built around your group.",
        },
      ],
    },
    location: {
      eyebrow: "The Cartago Highlands",
      title: "A quieter side of Costa Rica.",
      body: "Away from the humid coastline, the mountains of Cartago hold a crisp, spring-like climate all year. Here, the Irazú Volcano rises above misty cloud forests and emerald valleys — a setting made for quiet reflection and time together as a family.",
      pin: "Cartago, Costa Rica — mountain elevation",
      imageAlt: "Cartago cloud forest mountains at sunrise, with tropical birds in flight",
    },
    scrollStory: {
      imageAlt: "Montage of luxury kosher moments in Costa Rica",
      imageEyebrow: "A Curated Escape",
      imageTitle: "The Pura Shalom Experience",
      stages: [
        {
          label: "STAGE 01",
          title: "Seamless Arrival",
          body: "A private transfer from San José International Airport, straight up to the mountains. Your driver — local, English-speaking, and waiting with cold towels and a kosher refreshment for the ride.",
        },
        {
          label: "STAGE 02",
          title: "A Home in the Mountains",
          body: "Step into a private villa or cloud-forest suite, designed from the ground up with Jewish life in mind — thoughtful layouts, dual sinks, a kosher kitchenette, and Shabbat-friendly lighting throughout.",
        },
        {
          label: "STAGE 03",
          title: "Chef-Driven Dining",
          body: "Three meals a day, each one considered. Our culinary team draws on Costa Rica's volcanic soil, fresh palm hearts, and premium kosher meats — we'll confirm kashrut details when you reach out.",
        },
        {
          label: "STAGE 04",
          title: "A Shabbat Apart",
          body: "Shabbat here is unhurried. A phone-free retreat wrapped in mountain mist, with festive communal meals, guest speakers, heartfelt tefillah, and the melodies you know from home.",
        },
        {
          label: "STAGE 05",
          title: "Excursions, on Your Terms",
          body: "A private volcano hike, a custom zip-line run, or a sunset catamaran sail — every outing is timed around prayer schedules and kashrut needs.",
        },
      ],
    },
    dining: {
      eyebrow: "Culinary Excellence",
      title: "Kosher dining, without compromise.",
      body: "Our culinary team builds daily menus around the best of Costa Rica. We'll confirm kosher standards when you reach out, and every meal is shaped by your family's needs and the season of your stay.",
      checklist: [
        {
          title: "Glatt / Mehadrin Standards",
          body: "We'll walk you through our kosher standards when you inquire, and can accommodate Mehadrin preferences with advance notice.",
        },
        {
          title: "Volcanic Farm-to-Table",
          body: "Organic greens, berries, herbs, and highland coffee, picked from neighboring farms.",
        },
      ],
      imageAlt: "Gourmet kosher dining with roasted vegetables and mountain valley views",
    },
    jewishLife: {
      eyebrow: "A Life of Faith",
      title: "Built around the rhythm of Jewish life.",
      subtitle: "Jewish life support is available on request, with Shabbat-friendly hospitality woven throughout your stay.",
      cards: [
        {
          title: "Jewish Life Support",
          body: "Prayer arrangements, Shabbat hospitality, and thoughtful coordination for your group — available whenever you need them.",
        },
        {
          title: "Shabbat Experience",
          body: "Shabbat-friendly hospitality in a peaceful mountain setting — communal meals, a calm atmosphere, and true rest in nature.",
        },
        {
          title: "Torah & Learning",
          body: "Shiurim, chavruta, and guest speakers on request — tailored to your group's interests and level of observance.",
        },
      ],
      imageAlt: "Shabbat table setting at a kosher mountain retreat",
    },
    family: {
      eyebrow: "For All Generations",
      title: "A real, peaceful vacation for parents, too.",
      heroBadge: "FAMILY RETREAT",
      heroTitle: "A Retreat Built for Families",
      heroBody: "Private hospitality for families and groups — spacious suites, supervised nature activities, and programming that lets parents actually rest.",
      heroImageAlt: "Children exploring butterflies on a tropical nature walk",
      miniCards: [
        { label: "01 / COMFORT", title: "Family Suites" },
        { label: "02 / NATURE", title: "Guided Activities" },
        { label: "03 / DINING", title: "Flexible Meals" },
        { label: "04 / DISCOVER", title: "Family Excursions" },
      ],
    },
    carousel: {
      eyebrow: "Life at Pura Shalom",
      title: "Luxury at your fingertips.",
      items: [
        { label: "AQUATICS", title: "Infinity Cloud Pool", alt: "Infinity cloud pool at sunset" },
        { label: "RELAXATION", title: "Lava Stone Spa", alt: "Lava stone spa treatment room" },
        { label: "STARRY EVENINGS", title: "Starlight Lounge", alt: "Tropical resort pool surrounded by lush palm trees and jungle hillside" },
        { label: "WELLNESS", title: "Sunrise Yoga Deck", alt: "Mountain lodge overlooking lush green valleys and tropical hills" },
        { label: "ARRIVAL", title: "Palm-Lined Drive", alt: "A lush, palm-lined driveway leading through tropical grounds toward a thatched-roof villa" },
        { label: "VISTAS", title: "Misty Mountain Balcony", alt: "A scenic view of misty tropical mountains from a white-railed balcony" },
      ],
    },
    experiences: {
      eyebrow: "Alpine Adventures",
      title: "Adventure, curated for the observant.",
      subtitle: "Private tours that respect your kashrut and your schedule.",
      cards: [
        { badge: "Peak Tour", title: "Irazú Volcano Expedition", alt: "Irazu Volcano Crater" },
        { badge: "Waterfall Hike", title: "Highland Waterfalls", alt: "Highland waterfall in the Costa Rican hills" },
        { badge: "Canopy Tour", title: "Jungle Canopy Adventure", alt: "Jungle canopy zip line" },
        { badge: "Sunset Sail", title: "Pacific Sunset Cruise", alt: "Sunset catamaran cruise" },
      ],
    },
    rooms: {
      eyebrow: "Accommodations",
      title: "Comfort for couples and groups.",
      body: "Every suite and villa is thoughtfully designed with private sleeping arrangements, kosher kitchen amenities, and Shabbat-friendly systems.",
      cta: "Explore Rooms",
      fromPrice: "Available upon request",
      perNight: "",
      selectPlanner: "Plan Your Stay",
      items: {
        "panorama-villa": {
          name: "The Panorama Villa",
          category: "Villa Collection",
          description: "A four-bedroom villa with soaring cedar ceilings, sweeping volcano views, a private heated plunge pool, and a fully equipped kosher kitchen with dual sinks.",
          features: ["Private Heated Pool", "Fully Equipped Kosher Kitchen", "Panoramic Balcony", "On-site Butler", "Shabbat-Friendly Lighting"],
        },
        "cloud-forest-suite": {
          name: "Cloud Forest Suite",
          category: "Suites",
          description: "A quiet retreat for two, with rich oak and linen textures, a private outdoor rain shower, and a garden terrace overlooking the valley.",
          features: ["Private Garden Terrace", "Outdoor Rain Shower", "Twin or King Bedding", "Kosher Espresso Bar", "Premium Linens"],
        },
      },
    },
    programs: {
      eyebrow: "Seasonal Retreats",
      title: "A Season for Every Family",
      subtitle: "Seasonal packages throughout the Jewish year.",
      cards: [
        {
          title: "Passover",
          body: "The seder, under equatorial stars. A fully inclusive, Glatt kosher Pesach program with chef-driven dining, kids' camps, and guest scholars.",
          cta: "Request Passover Rates",
        },
        {
          title: "Sukkot",
          body: "Celebrate in our mountain sukkah, overlooking the emerald valley below. Tefillah, a lulav and etrog concierge, and activities throughout Chol HaMoed.",
          cta: "Inquire About Sukkot",
        },
        {
          title: "Winter Retreats",
          body: "Trade the cold for crisp highland sun. Active weeks built for family camps and zip-line adventures.",
          cta: "Learn More",
        },
      ],
    },
    trust: {
      title: "The details matter. We plan for them.",
      stats: [
        { value: "100%", label: "Glatt Kosher Certification" },
        { value: "24/7", label: "Dedicated Concierge" },
        { value: "Private", label: "Airport Transfers" },
        { value: "Secure", label: "Private Mountain Estate" },
      ],
    },
    finalCta: {
      eyebrow: "Begin Your Stay",
      title: "The mountains are waiting.",
      body: "Our team is ready to help plan your stay — we'll confirm kosher standards and every detail when you reach out.",
      cta: "Plan Your Stay",
    },
    footer: {
      brand: "Pura Shalom",
      description: "A Glatt kosher mountain retreat in Cartago, Costa Rica.",
      badges: ["Glatt Kosher", "Shabbat Observant"],
      newsletterLabel: "Newsletter",
      emailPlaceholder: "Enter your email",
      subscribe: "Subscribe",
      exploreTitle: "Explore",
      exploreLinks: ["The Promise", "Location", "Kosher Dining", "Accommodations"],
      inquireTitle: "Inquire",
      inquireLinks: ["Plan Your Stay", "Concierge AI"],
      location: "Cartago, Costa Rica",
      copyright: "© 2026 Pura Shalom. All rights reserved. A Glatt kosher mountain retreat in Costa Rica.",
    },
    planner: {
      eyebrow: "Retreat Planner",
      title: "Plan your stay, your way.",
      subtitle: "Set your dates, kosher preferences, excursions, and family programs to get a real-time estimate and send your inquiry to our team.",
      steps: {
        guestDetails: "Guest Details",
        accommodation: "Select Accommodation",
        kashrut: "Kashrut & Jewish Life",
        excursions: "Excursions & Adventures",
        family: "Family Programs",
        special: "Special Requests & Dietary Preferences",
      },
      labels: {
        fullName: "FULL NAME",
        email: "EMAIL ADDRESS",
        phone: "PHONE NUMBER",
        season: "PREFERRED SEASON / MONTH",
        nights: "NUMBER OF NIGHTS",
        adults: "ADULT GUESTS (13+)",
        children: "CHILDREN (0-12)",
        supervision: "SUPERVISION STANDARDS",
        dailyServices: "DAILY SERVICES",
        shabbatDining: "COMMUNAL SHABBAT DINING",
        communalSeats: "Communal seat allocations:",
        rate: "RATE",
        perNight: "/ Night",
        perPerson: "/ Person",
        perDay: "/ Day",
        perNightChild: "PER NIGHT / CHILD",
        estimatedTotal: "ESTIMATED TOTAL",
        subjectReview: "Subject to advisor review",
        privateTour: "PRIVATE TOUR",
        communal: "COMMUNAL",
      },
      placeholders: {
        fullName: "E.g., Jonathan Goldstein",
        email: "goldstein@example.com",
        phone: "+1 (555) 300-4000",
        season: "December 2026 / Chanukah",
        specialRequests: "For example: We're celebrating our anniversary and keep Cholav Yisrael strictly. We'd also love help arranging a short Torah study session for our son on Monday morning...",
      },
      accommodationHint: "Choose the space that best fits your group. Dual sinks, private sleeping arrangements, and Shabbat-friendly systems are built into every category.",
      kashrutHint: "Our kitchen operates 100% Glatt Kosher, Pas Yisrael, and Cholav Yisrael. You're welcome to select specific kashrut preferences below.",
      minyanLabel: "Reserve Seats in Synagogue",
      minyanHint: "Reserve seating in the shul for Shacharit, Mincha, and Maariv. Siddurim and chumashim are provided.",
      shabbatHint: "Reserve a table at our Shabbat meal — kiddush cups, fresh challah, and a warm communal atmosphere.",
      excursionsHint: "Add private nature hikes or zip-line adventures to your stay. Every excursion is timed around minyan and kashrut needs.",
      familyHint: "Supervised rainforest camps, a teen lounge, and childcare, so you can relax with real peace of mind.",
      specialHint: "Let us know about accessibility needs, kashrut supervision, allergies, or milestone celebrations — anniversaries, bar or bat mitzvahs, family reunions.",
      submit: "Submit Inquiry & Reserve Your Spot",
      estimateTitle: "Your Estimate",
      nightsAdults: "nights ×",
      adultsWord: "adults",
      kidsWord: "kids",
      supervisionSurcharge: "Supervision Surcharge",
      curatedExcursions: "SELECTED EXCURSIONS",
      familyProgramming: "FAMILY PROGRAMMING",
      inclusionsTitle: "Standard Inclusions:",
      inclusionsBody: "Three kosher meals daily, airport transfer, full synagogue access, and on-site amenities (pool, yoga deck, and catamaran outing if selected).",
      pledgeTitle: "Our Booking Pledge",
      pledgeBody: "Submitting this inquiry holds your spot in our retreat. A member of our team will reach out by email or phone within 24 hours to review your schedule, go over any special requests, and finalize the reservation.",
      adultsOption: "Adults",
      childrenOption: "Children",
      guestsOption: "Guests",
      validationAlert: "Please fill in your name, email, and phone number to request availability.",
      kashrutTiers: {
        "glatt-standard": {
          name: "Glatt Kosher (CRC / OU)",
          description: "Full-time mashgiach, Pas Yisrael, and Cholav Yisrael standard.",
        },
        "beit-yosef": {
          name: "Beit Yosef Standard",
          description: "Strict Sephardic Beit Yosef meat standards, under close supervision.",
        },
        chassidish: {
          name: "Chassidishe Shechita / Super-Strict",
          description: "The highest chassidishe kashrut standards, with custom hashgacha verification.",
        },
      },
      activities: {
        volcano: {
          name: "Irazú Volcano Expedition",
          description: "A private guided tour of the active crater, volcanic ash fields, and misty peaks of Cartago, with a packed Glatt kosher lunch included.",
          category: "Adventure",
        },
        waterfalls: {
          name: "Secret Rainforest Waterfalls Hike",
          description: "Hidden waterfalls tumbling into turquoise pools, with an experienced naturalist guide. Paths can be adjusted to fit your group's pace.",
          category: "Nature",
        },
        canopy: {
          name: "Jungle Canopy Zipline Tour",
          description: "Zip above the cloud forest canopy with expert safety guides and sweeping views of the emerald valley below.",
          category: "Adrenaline",
        },
        "sunset-sail": {
          name: "Private Sunset Catamaran Cruise",
          description: "A private sunset sail aboard a teak-decked luxury catamaran, with Glatt kosher hors d'oeuvres and wine on board.",
          category: "Leisure",
        },
      },
      familyServices: {
        "kids-camp": {
          name: "Rainforest Kid's Camp",
          description: "Guided butterfly walks, nature art, and rainforest exploration for kids.",
        },
        nanny: {
          name: "Private Nanny Service",
          description: "Trained, on-demand childcare whenever you need it.",
        },
        "teen-lounge": {
          name: "Teen Lounge Access",
          description: "Billiards, arcade games, and guided hiking treks for teens.",
        },
      },
    },
    chat: {
      eyebrow: "Ask Us Anything",
      title: "Concierge AI",
      subtitle: "Ask about kashrut details, minyan schedules, babysitting, private excursions, or the weather in the mountains.",
      conciergeName: "The Pura Shalom Concierge",
      conciergeRole: "Hospitality Advisor",
      poweredBy: "Powered by Gemini",
      loading: "The Concierge is preparing a few suggestions...",
      placeholder: "Ask about kashrut, Shabbat, rooms, excursions, or the weather...",
      welcome: `Shalom, and welcome. I'm the Pura Shalom Concierge, here to help you plan your stay.

I can help with kosher details, volcano excursions, and anything related to Jewish life during your time here in the mountains of Cartago, Costa Rica.

What can I help you with today? Feel free to ask about our rooms, dining, Shabbat, or local excursions.`,
      errorFallback: "I'm sorry — it looks like I ran into a brief connection issue. Our team is here and happy to help directly through our inquiry form. Please submit your request there.",
      emptyResponse: "I'm here to help. Let me know what you need.",
      suggestions: [
        "What are your kosher standards?",
        "Tell me about the Panorama Villa.",
        "What's Shabbat like at Pura Shalom?",
        "What's the weather like in the mountains of Cartago?",
        "Can you arrange a private tour of the Irazú Volcano?",
      ],
    },
    inquiries: {
      eyebrow: "Your Travel Advisor",
      title: "My Inquiries",
      subtitle: "Track your requests, download your estimate, and keep an eye on your countdown to Costa Rica.",
      emptyTitle: "No Inquiries Yet",
      emptyBody: "You haven't submitted an inquiry yet. Visit the planner to build your first stay.",
      emptyCta: "Open the Planner",
      submittedLabel: "SUBMITTED INQUIRIES",
      createNew: "+ Create New Plan",
      statusReview: "ADVISOR REVIEW IN PROGRESS",
      submittedOn: "Submitted on",
      countdownLabel: "PURA SHALOM COUNTDOWN",
      countdownTitle: "Your Costa Rica retreat awaits!",
      countdownBody: "A member of our team will reach out to",
      countdownBodyOr: "or",
      countdownBodyEnd: "shortly to confirm pricing and lock in your dates.",
      daysLabel: "DAYS UNTIL YOUR STAY",
      specsTitle: "STAY DETAILS",
      programmingTitle: "SELECTED ACTIVITIES",
      noActivities: "You haven't selected any excursions yet. You can add them with your advisor.",
      specialTitle: "Special Requests & Accommodations",
      costTitle: "ESTIMATED COST",
      costSubtitle: "All-Inclusive Retreat Package",
      costNote: "Final pricing may vary by season",
      glattIncluded: "Glatt certification included",
      primaryContact: "Primary Contact:",
      bespokeDates: "Your Dates:",
      adultGuests: "Adult Guests:",
      kashrutSelection: "Kashrut Selection:",
      adultsSuffix: "Adults",
      deleteConfirm: "Are you sure you want to cancel this inquiry?",
      printTitle: "Print Estimate",
      deleteTitle: "Cancel Inquiry",
      statusPending: "Pending",
    },
    heroImageAlt: "Mountain valley view at a luxury kosher retreat in Cartago, Costa Rica",
  },
  he: {
    nav: {
      logo: "Pura Shalom",
      home: "בית",
      rooms: "חדרים ובקתות",
      holidays: "חגים וחופשות",
      pesach: "נופש פסח",
      sukkot: "נופש סוכות",
      yearRound: "חופשות לאורך השנה",
      kosherJewishLife: "אוכל",
      costaRicaGuide: "מדריך קוסטה ריקה",
      faq: "שאלות נפוצות",
      contact: "יצירת קשר",
      planYourStay: "תכננו את החופשה",
      diningKashrut: "אוכל וכשרות",
      jewishLife: "חיים יהודיים",
      experiences: "חוויות",
      searchPlaceholder: "חיפוש",
      phone: "",
      phoneAria: "התקשרו ל-Pura Shalom",
      contactLinkAria: "צרו קשר",
      menuOpenAria: "פתחו תפריט",
      menuCloseAria: "סגרו תפריט",
      /** @deprecated legacy tab navigation — preserved for LegacyTabApp */
      discover: "גלו",
      planner: "התאמה אישית",
      inquiries: "הפניות שלי",
      chat: "קונסיירז' AI",
      cta: "בדקו זמינות",
    },
    pages: pagesHe,
    hero: {
      eyebrow: "קרטגו, קוסטה ריקה",
      titleBefore: "ריטריט כשר יוקרתי ",
      titleEmphasis: "בהרי",
      titleAfter: " קוסטה ריקה",
      ctaPrimary: "תכננו את השהייה",
      ctaSecondary: "לחדרים",
      scroll: "גלילה",
    },
    promise: {
      eyebrow: "אירוח ללא פשרות",
      title: "מגיעים. הכול כבר מוכן.",
      body: "מתכנון כשרות מוקפד ועד אווירה הררית שקטה — אנחנו דואגים לכל פרט, כדי שתגיעו בביטחון וברוגע.",
      cards: [
        {
          title: "אוכל כשר",
          body: "פרטי הכשרות יאושרו בשיחת התאמה. תפריטים בהובלת שף, מותאמים לצרכי המשפחה ולעונת השהייה.",
        },
        {
          title: "חיים יהודיים",
          body: "אפשרות לתיאום צרכים יהודיים מראש, עם אירוח מותאם שבת לאורך כל השהייה.",
        },
        {
          title: "ריטריט משפחתי",
          body: "חוויה משפחתית יוקרתית ושקטה — לינה מרווחת, פינות מנוחה ותכנון שמותאם לגודל הקבוצה.",
        },
      ],
    },
    location: {
      eyebrow: "מקדש ההרים בקרטגו",
      title: "צד שקט יותר של קוסטה ריקה.",
      body: "רחוק מקווי החוף הלחים, הרי קרטגו הגבוהים מציעים אקלים אלפיני נעים וקריר. כאן, הר הגעש איראסו המרהיב שורר מעל יערות עננים ירוקים ועמקים אזמרגד — נוף של שלווה עמוקה, מושלם להתבוננות רוחנית ולחיבור משפחתי.",
      pin: "קרטגו, קוסטה ריקה (גובה אלפיני)",
      imageAlt: "יער עננים ירוק בקרטגו בשעות הזריחה עם ציפורים טרופיות",
    },
    scrollStory: {
      imageAlt: "רגעים כשרים יוקרתיים בקוסטה ריקה",
      imageEyebrow: "חופשה מותאמת אישית",
      imageTitle: "האירוח המוקפד שלנו",
      stages: [
        {
          label: "שלב 01",
          title: "הגעה חלקה",
          body: " הסעה פרטית פרימיום משדה התעופה הבינלאומי של סן חוסה ישירות אל הריטריט בהרים. נהג מקומי פרטי דובר אנגלית ממתין לכם עם מגבות רעננות וכיבוד כשר.",
        },
        {
          label: "שלב 02",
          title: "מקדש ללא פשרות",
          body: "היכנסו לווילות פרטיות או לסוויטות בעננים, שתוכננו מהיסוד עם החיים הרוחניים שלכם בראש — פריסות מותאמות, כיורים כפולים, מטבחונים כשרים ומערכות שבת אלקטרוניות.",
        },
        {
          label: "שלב 03",
          title: "ארוחות כשרות ברמה עולמית",
          body: "טעמו שלוש ארוחות gourmet ביום. צוותי המטבח המובילים משלבים תוצרת אדמת געשית מקומית, לבבות דקל ובשר כשר פרימיום — עם פרטי כשרות שיאושרו בשיחת התאמה.",
        },
        {
          label: "שלב 04",
          title: "שבת של הרמוניה",
          body: "התחברו לעומק בשבת. היכנסו למקום קדוש וללא טלפונים, מוקף בערפל מתגלגל — עם סעודות חגיגיות, הרצאות מעוררות השראה, תפילה יפה וזמירות מסורתיות.",
        },
        {
          label: "שלב 05",
          title: "טיולים מוקפדים",
          body: "גלו טיפוסים פרטיים לפסגות געשיות, מסלולי זipline מותאמים או שייט קטמרן לשקיעה. כל מסלול מכבד את זמני התפילה ואת מגבלות הכשרות.",
        },
      ],
    },
    dining: {
      eyebrow: "מצוינות קולינרית",
      title: "אוכל כשר, ללא פשרות.",
      body: "צוות הקולינריה שלנו מכין תפריטים יומיים החוגגים את שפע קוסטה ריקה. פרטי הכשרות יאושרו בשיחת התאמה, עם אוכל בהובלת שף המותאם לצרכי המשפחה ולעונת השהייה.",
      checklist: [
        {
          title: "סטנדרטי גלאט / מהדרין",
          body: "פרטי הכשרות יאושרו בשיחת התאמה. העדפות מהדרין ניתנות לאירוח כשמתואמות מראש.",
        },
        {
          title: "מהשדה אל השולחן — אדמת געש",
          body: "ירקות, פירות יער, עשבי תיבול וקפה מהרים — מגידולים אורגניים מחוות שכנות.",
        },
      ],
      imageAlt: "אוכל כשר יוקרתי עם ירקות קלו ונוף עמק הרים",
    },
    jewishLife: {
      eyebrow: "כוונה רוחנית",
      title: "בנוי סביב קצב החיים היהודי.",
      subtitle: "אפשרות לתיאום צרכים יהודיים מראש, עם אירוח מותאם שבת לאורך השהייה.",
      cards: [
        {
          title: "תמיכה בחיים יהודיים",
          body: "אפשרות לתיאום צרכים יהודיים מראש — הסדרי תפילה, אירוח שבת ותיאום מחשבה לקבוצה שלכם.",
        },
        {
          title: "חוויית שבת",
          body: "אירוח מותאם שבת בסביבה הררית שקטה — ארוחות קהילתיות, אווירה רגועה ומרחב למנוחה אמיתית בטבע.",
        },
        {
          title: "תורה ולימוד",
          body: "שיעורים, חברותא ומלומדים מבקרים לפי בקשה — מותאם לרמת העניין והשמירה של הקבוצה.",
        },
      ],
      imageAlt: "שולחן שבת בריטריט כשר בהרים",
    },
    family: {
      eyebrow: "לכל הדורות",
      title: "חופשה אמיתית ושקטה גם להורים.",
      heroBadge: "ריטריט משפחתי",
      heroTitle: "חוויה משפחתית יוקרתית ושקטה",
      heroBody: "אירוח פרטי למשפחות וקבוצות — סוויטות מרווחות, פעילויות טבע מלוות ותכנון שמאפשר להורים באמת לנוח.",
      heroImageAlt: "ילדים חוקרים פרפרים במסלול טבע טרופי",
      miniCards: [
        { label: "01 / נוחות", title: "סוויטות משפחה" },
        { label: "02 / טבע", title: "פעילויות מודרכות" },
        { label: "03 / אוכל", title: "ארוחות גמישות" },
        { label: "04 / גילוי", title: "טיולים משפחתיים" },
      ],
    },
    carousel: {
      eyebrow: "החיים בפורה שלום",
      title: "יוקרה בהישג יד.",
      items: [
        { label: "מים", title: "בריכת עננים אינסוף", alt: "בריכת עננים אינסוף בשקיעה" },
        { label: "מנוחה", title: "סpa אבן געש", alt: "חדר טיפולי סpa מאבן געש" },
        { label: "ערבים מכוכבים", title: "טרקלין Starlight", alt: "בריכת נופש טרופית מוקפת דקלים וגבעות ג'ונגל" },
        { label: "בריאות", title: "מרפסת יוגה לזריחה", alt: "לodge הרים עם נוף לעמקים ירוקים וגבעות טרופיות" },
        { label: "הגעה", title: "שדרת דקלים", alt: "שדרה ירוקה מוקפת דקלים המובילה לווילה עם גג קש" },
        { label: "נופים", title: "מרפסת הרים בערפל", alt: "נוף הרים טרופיים מערפל ממרפסת עם מעקה לבן" },
      ],
    },
    experiences: {
      eyebrow: "הרפתקאות אלפיניות",
      title: "הרפתקה, מותאמת לשומרי מצוות.",
      subtitle: "טיולים פרטיים שמכבדים את הכשרות ואת לוח הזמנים שלכם.",
      cards: [
        { badge: "טיול פסגה", title: "משלחת להר איראסו", alt: "מכתש הר הגעש איראסו" },
        { badge: "טיול מפלים", title: "מפלי ההרים", alt: "מפל מים בהרי קוסטה ריקה" },
        { badge: "טיול חופות", title: "חוויית חופות בג'ונגל", alt: "מסלול zip line ביער הג'ונגל" },
        { badge: "שייט שקיעה", title: "שייט שקיעה באוקיינוס", alt: "שייט קטמרן בשקיעה" },
      ],
    },
    rooms: {
      eyebrow: "חדרי יוקרה",
      title: "נוחות לזוגות ולקבוצות.",
      body: "כל סוויטה ווילה תוכננו בקפידה עם אפשרות להפרדת מיטות, מתקני מטבח כשר ומערכות תואמות שבת.",
      cta: "גלו את החדרים",
      fromPrice: "זמין לפי בקשה",
      perNight: "",
      selectPlanner: "תכננו את השהייה",
      items: {
        "panorama-villa": {
          name: "וילת Panorama",
          category: "אוסף הווילות",
          description: "יצירת מופת אדריכלית בת 4 חדרי שינה, עם תקרות ארז גבוהות, נוף מרהיב ל הר הגעש, בריכת שחייה פרטית מחוממת ומטבחון כשר מצויד עם כיורים כפולים.",
          features: ["בריכה פרטית מחוממת", "מטבח כשר מצויד", "מרפסה פנורמית", "משרת אישי", "הגדרות מנורות שבת"],
        },
        "cloud-forest-suite": {
          name: "סוויטת Cloud Forest",
          category: "סוויטות",
          description: "מקלט אינטימי ושקט לזוגות, עם טקסטורות אלון ופשתן איכותיות, מקלחת גשם חיצונית פרטית וטרסת גינה רחבה עם נוף לעמק.",
          features: ["טרסת גינה פרטית", "מקלחת גשם חיצונית", "מיטות נפרדות/זוגיות", "בר אסpresso כשר", "מצעים יוקרתיים"],
        },
      },
    },
    programs: {
      eyebrow: "עונות מותאמות",
      title: "לוח שנה של Sanctuary.",
      subtitle: "חבילות עונתיות מיוחדות לאורך השנה היהודית.",
      cards: [
        {
          title: "פסח",
          body: "סeder אולטימטיבי תחת כוכבי הקוואטר. תוכניות קולינריות גלאט כשר לפesach, מחנות ילדים ומלומדים — הכול כלול.",
          cta: "בקשו מחירי פסח",
        },
        {
          title: "סוכות",
          body: "סעדו בסוכה ההררית המרהיבה שלנו עם נוף לעמקים אזמרגד. תפילות יפות, קונסיירז' לulav ואתrog, ופעילויות חול המoed.",
          cta: "הזמינו חבילת סוכות",
        },
        {
          title: "ריטריטים חורפיים",
          body: "תהנו משמש הרים צלולה בחורף הצפוני. שבועות פעילים מותאמים למחנות משפחתיים ולמשלחות zip מרגשות.",
          cta: "למידע נוסף",
        },
      ],
    },
    trust: {
      title: "הפרטים חשובים. אנחנו מתכננים אותם.",
      stats: [
        { value: "100%", label: "תעודת גלאט כשר" },
        { value: "24/7", label: "קונסיירז' ייעודי" },
        { value: "פרטי", label: "הסעות שדה תעופה" },
        { value: "מאובטח", label: "אחוזה וולקנית פרטית" },
      ],
    },
    finalCta: {
      eyebrow: "התחילו את המסע",
      title: "חוו יוקרה מוחלטת.",
      body: "צוות האירוח שלנו מוכן לתאם את ריטריט ההרים המותאם אישית שלכם — עם פרטי כשרות שיאושרו בשיחת התאמה.",
      cta: "תכננו את השהייה",
    },
    footer: {
      brand: "Pura Shalom",
      description: "ריטריט כשר יוקרתי ברמת גלאט, בין הרי קרטגו הבתוליים בקוסטה ריקה.",
      badges: ["גלאט כשר 24/7", "שומר שבת"],
      newsletterLabel: "ניוזלטר VIP",
      emailPlaceholder: "הזינו את האימייל שלכם",
      subscribe: "הרשמה",
      exploreTitle: "גלו",
      exploreLinks: ["ההבטחה", "המיקום", "אוכל כשר", "לינה"],
      inquireTitle: "פנו אלינו",
      inquireLinks: ["חבילה מותאמת", "קונסיירז' AI"],
      location: "קרטגו, קוסטה ריקה",
      copyright: "© 2026 Pura Shalom. כל הזכויות שמורות. ריטריט הרים כשר יוקרתי בקוסטה ריקה.",
    },
    planner: {
      eyebrow: "מתכנן Sanctuary",
      title: "התאימו אישית את הריטריט היוקרתי.",
      subtitle: "הגדירו תאריכים, פרמטרי כשרות, טיולים ותכניות משפחתיות — וקבלו הצעת מחיר בזמן אמת להגשת פנייה לצוות הייעוץ שלנו.",
      steps: {
        guestDetails: "פרטי אורח",
        accommodation: "בחירת לינה",
        kashrut: "כשרות וחיים יהודיים",
        excursions: "טיולים והרפתקאות",
        family: "תכניות משפחתיות",
        special: "בקשות מיוחדות והעדפות תזונה",
      },
      labels: {
        fullName: "שם מלא",
        email: "כתובת אימייל",
        phone: "מספר טלפון",
        season: "עונה / חודש מועדף",
        nights: "מספר לילות",
        adults: "מבוגרים (13+)",
        children: "ילדים (0-12)",
        supervision: "סטандарטי השגחה",
        dailyServices: "שירותים יומיים",
        shabbatDining: "סעודות שבת קהילתיות",
        communalSeats: "הקצאת מקומות:",
        rate: "תעריף",
        perNight: " / לילה",
        perPerson: " / לאדם",
        perDay: " / יום",
        perNightChild: "ללילה / ילד",
        estimatedTotal: "סה״כ משוער",
        subjectReview: "בכפוף לבדיקת יועץ",
        privateTour: "טיול פרטי",
        communal: "קבוצתי",
      },
      placeholders: {
        fullName: "לדוגמה: יonathan כהן",
        email: "example@email.com",
        phone: "+972 50-000-0000",
        season: "דצמבר 2026 / חנוכה",
        specialRequests: "לדוגמה: אנחנו חוגגים יום נישואין כסף. נדרש חלב ישראל בלבד, ונשמח לסיוע בלימוד תורה פרטי לבננו ביום שני בבוקר...",
      },
      accommodationHint: "בחרו את החלל האדריכלי המתאים לקבוצה שלכם. כיורים כפולים, חדרי שינה נפרדים ופרמטרים תואמי שבת — משולבים במלואם.",
      kashrutHint: "תוכנית הקולינריה שלנו 100% גלאט כשר, פת ישראל וחלב ישראל. ניתן לבחור פרמטרי כשרות מתקדמים למטה.",
      minyanLabel: "שריון מקומות בבית הכנסת",
      minyanHint: "שריון מרווח מקומות בבית הכנסת לשחרית, מנחה וערבית. כולל סידורים וחומשים.",
      shabbatHint: "שריון שולחן פרטי בסעודת השבת הקהילתית המרהיבה שלנו, עם גביעי קידוש מכסף וחלות מקולפות.",
      excursionsHint: "התאימו את החופשה עם מסלולי טבע פרטיים או ריצות zipline. כל טיול מתוזמן סביב מניינים ומגבלות כשרות.",
      familyHint: "מחנות גשם מלווים, טרקלין לבני נוער ושירותי childcare — כדי שתוכלו להירגע בשקט מוחלט.",
      specialHint: "ספרו לצוות הייעוץ שלנו על צרכי נגישות, השגחות כשרות מיוחדות, אלרגיות או חגיגות (יום נישואין, בר מצווה, reunion משפחתי).",
      submit: "שלחו פנייה ושריינו מקום",
      estimateTitle: "הערכת מחיר מותאמת",
      nightsAdults: "לילות ×",
      adultsWord: "מבוגרים",
      kidsWord: "ילדים",
      supervisionSurcharge: "תוספת השגחה",
      curatedExcursions: "טיולים מוקפדים",
      familyProgramming: "תכניות משפחתיות",
      inclusionsTitle: "כלול בסטандарт:",
      inclusionsBody: "3 ארוחות gourmet גלאט כשר ביום, הסעה משדה התעופה, גישה מלאה לבית הכנסת, מתקני פנאי (בריכת אינסוף, מרפסת יוגה — ללא שייט קatamaran אלא אם נבחר).",
      pledgeTitle: "התחייבות ההזמנה שלנו",
      pledgeBody: "הגשת הפנייה שומרת על מקומכם בעדיפות. קונסיירז' יוקרתי יצור קשר תוך 24 שעות לסקירת לוח הזמנים, לכיוון בקשות מיוחדות ולסגירת ההזמנה.",
      adultsOption: "מבוגרים",
      childrenOption: "ילדים",
      guestsOption: "אורחים",
      validationAlert: "אנא מלאו שם, אימייל ומספר טלפון כדי לבקש זמינות.",
      kashrutTiers: {
        "glatt-standard": {
          name: "גלאט כשר (CRC / OU)",
          description: "משגיח תמידי מלא, פת ישראל וחלב ישראל.",
        },
        "beit-yosef": {
          name: "סטандарт בית יוסף",
          description: "בשר בית יוסף ספרדי מחמיר תחת השגחה גבוהה.",
        },
        chassidish: {
          name: "שחיטה חסidית / מחמיר במיוחד",
          description: "סטандартי כשרות חסidיים הגבohים ביותר, אימות hashgacha מותאם.",
        },
      },
      activities: {
        volcano: {
          name: "משלחת ל הר איראסו",
          description: "סיור פרטי מguided ב מכתש הפעיל, שדות אפר געשי ופסגות מעורפלות — עם ארוחת צהריים כשרה ארוזה.",
          category: "הרפתקה",
        },
        waterfalls: {
          name: "טיול למפלי הגשם הסודיים",
          description: "גלו מפלים נסתרים בבריכות טורקיז, עם naturalists מקצועיים. מסלולים מותאמים לכושר האורחים.",
          category: "טבע",
        },
        canopy: {
          name: "מסלול Zipline בח canopy",
          description: "עופו בבטחה מעל ח canopy יער העננים. אמצעי בטיחות יוצאי דופן ונוף עמק אזמרגד מלמעלה.",
          category: "אדרנalin",
        },
        "sunset-sail": {
          name: "שייט קטמרן פרטי לשקיעה",
          description: "עלו לסיפon teak נקי של יacht יוקרתי בשקיעה. כולל מנות כשרות גלאט ואפשרות לז pairing יין.",
          category: "פנאי",
        },
      },
      familyServices: {
        "kids-camp": {
          name: "מחנה ילדים ביער הגשם",
          description: "טיולי פרפרים מguided, אמנות בוטנית וחקירת טבע טרופית.",
        },
        nanny: {
          name: "שירות מטפלת פרטית",
          description: "טיפול ילדים יוקרתי מקצועי לפי דרישה.",
        },
        "teen-lounge": {
          name: "גישה לטרקלין בני נוער",
          description: "biljard, ארcade, קונסolות משחק וטיולי hiking מguided לבני נוער.",
        },
      },
    },
    chat: {
      eyebrow: "סיוע בזמן אמת",
      title: "דesk קונסיירז' AI",
      subtitle: "שאלו על כשרות, מניינים, בייבי-sitter, מפלים פרטיים או מזג אוויר הררי.",
      conciergeName: "קונסיירז' The Sanctuary",
      conciergeRole: "יועץ אירוח יוקרתי",
      poweredBy: "מופעל על ידי Gemini",
      loading: "קונסיירז' The Sanctuary מכין הצעות מותאמות...",
      placeholder: "שאלו על כשרות, שבת, חדרים, טיולים ומזג אוויר...",
      welcome: `שלום וברוכים הבאים. אני "קונסיירז' The Sanctuary", יועץ האירוח היוקרתי האישי שלכם.

אני לשירותכם המלא לתיאום פרמטרי גלאט כשר, טיולי געש מותאמים ובקשות רוחניות — כאן בהרי קרטגו היפים והצלולים של קוסטה ריקה.

איך אוכל להתאים אישית את חופשת היוקרה שלכם? שאלו על החדרים, תעודת הכשרות, לוח השבת או טיולי יום.`,
      errorFallback: "מתנצלים, חלה תקלה קלה בחיבור לדesk. הריטריט הכשר שלנו פתוח במלואו — נשמח לסייע דרך טופס הפנייה!",
      emptyResponse: "אני כאן לסייע. ספרו לי במה אוכל לעזור.",
      suggestions: [
        "מהם סטандарטי הכשרות המחמירים שלכם?",
        "ספרו על מתקני וילת Panorama.",
        "איך נראית אווירת השבת ב-Altura?",
        "מה מזג האוויר בהרים בקרטagו?",
        "האם יש טיולים מותאמים ל הר איראסו?",
      ],
    },
    inquiries: {
      eyebrow: "לוח יועץ הנסיעות",
      title: "הפניות החופשה היוקרתיות שלי.",
      subtitle: "עקבו אחר בקשותיכם, הורידו הצעות מחיר, ועקבו אחר הספירה לאחור לחופשה.",
      emptyTitle: "לא נמצאו פניות פעילות",
      emptyBody: "עדיין לא הגשתם פנייה. בקרו במתכנן הריטריט כדי להתאים את החבילה הראשונה שלכם.",
      emptyCta: "פתחו את מתכנן הריטריט",
      submittedLabel: "פניות שהוגשו",
      createNew: "+ צרו תוכנית חדשה",
      statusReview: "בבדיקת יועץ",
      submittedOn: "הוגש ב-",
      countdownLabel: "ספירה לאחור ל-Altura",
      countdownTitle: "מקדש ההרים בקוסטה ריקה ממתין לכם!",
      countdownBody: "יועץ נסיעות כשר יוקרתי יצור קשר עם",
      countdownBodyOr: "או",
      countdownBodyEnd: "בקרוב לקביעת מחיר ותאריכים.",
      daysLabel: "ימים להרפיה",
      specsTitle: "פרטי ההזמנה",
      programmingTitle: "תכניות מוקפדות",
      noActivities: "לא נבחרו טיולים. ניתן לתאם עם היועץ.",
      specialTitle: "בקשות מיוחדות והעדפות",
      costTitle: "הערכת עלות זמנית",
      costSubtitle: "חבילת VIP כוללת",
      costNote: "בכפוף למכפילי עונה מקומיים",
      glattIncluded: "תעודת גלאט כלולה",
      primaryContact: "איש קשר:",
      bespokeDates: "תאריכים:",
      adultGuests: "מבוגרים:",
      kashrutSelection: "רמת כשרות:",
      adultsSuffix: "מבוגרים",
      deleteConfirm: "האם אתם בטוחים שברצונכם לבטל פנייה זו?",
      printTitle: "הדפסת הצעת מחיר",
      deleteTitle: "ביטול/מחיקת פנייה",
      statusPending: "ממתין",
    },
    heroImageAlt: "נוף עמק הררי בריטריט כשר יוקרתי בקרטגו, קוסטה ריקה",
  },
} as const;

export function getSiteContent(language: Language): SiteContent {
  return siteContent[language];
}
